MARKETS = {
    "all": "TÃ¼m Piyasalar",
    "turkey": "BIST / TÃ¼rkiye",
    "us": "ABD BorsasÄ±",
    "crypto": "Kripto",
    "precious": "DeÄŸerli Emtia",
    "energy": "Enerji",
    "forex": "Forex",
    "index": "Endeksler",
    "etf": "ETF",
}


ASSET_UNIVERSE = [
    # Crypto (live core)
    {"symbol": "BTCUSDT", "display": "BTCUSDT", "name": "Bitcoin", "assetClass": "crypto", "market": "crypto"},
    {"symbol": "ETHUSDT", "display": "ETHUSDT", "name": "Ethereum", "assetClass": "crypto", "market": "crypto"},
    {"symbol": "SOLUSDT", "display": "SOLUSDT", "name": "Solana", "assetClass": "crypto", "market": "crypto"},
    {"symbol": "BNBUSDT", "display": "BNBUSDT", "name": "BNB", "assetClass": "crypto", "market": "crypto"},
    {"symbol": "AVAXUSDT", "display": "AVAXUSDT", "name": "Avalanche", "assetClass": "crypto", "market": "crypto"},
    {"symbol": "XRPUSDT", "display": "XRPUSDT", "name": "XRP", "assetClass": "crypto", "market": "crypto"},
    {"symbol": "ADAUSDT", "display": "ADAUSDT", "name": "Cardano", "assetClass": "crypto", "market": "crypto"},
    {"symbol": "DOGEUSDT", "display": "DOGEUSDT", "name": "Dogecoin", "assetClass": "crypto", "market": "crypto"},
    # Crypto (seed coverage)
    {"symbol": "LTCUSDT", "display": "LTCUSDT", "name": "Litecoin", "assetClass": "crypto", "market": "crypto"},
    {"symbol": "LINKUSDT", "display": "LINKUSDT", "name": "Chainlink", "assetClass": "crypto", "market": "crypto"},
    {"symbol": "DOTUSDT", "display": "DOTUSDT", "name": "Polkadot", "assetClass": "crypto", "market": "crypto"},
    {"symbol": "TRXUSDT", "display": "TRXUSDT", "name": "TRON", "assetClass": "crypto", "market": "crypto"},
    {"symbol": "UNIUSDT", "display": "UNIUSDT", "name": "Uniswap", "assetClass": "crypto", "market": "crypto"},
    {"symbol": "MATICUSDT", "display": "MATICUSDT", "name": "Polygon", "assetClass": "crypto", "market": "crypto"},
    {"symbol": "NEARUSDT", "display": "NEARUSDT", "name": "NEAR", "assetClass": "crypto", "market": "crypto"},

    # Turkey (live core)
    {"symbol": "XU100.IS", "display": "BIST100", "name": "BIST 100", "assetClass": "index", "market": "turkey"},
    {"symbol": "THYAO.IS", "display": "THYAO", "name": "TÃ¼rk Hava YollarÄ±", "assetClass": "stock", "market": "turkey"},
    {"symbol": "GARAN.IS", "display": "GARAN", "name": "Garanti BBVA", "assetClass": "stock", "market": "turkey"},
    {"symbol": "AKBNK.IS", "display": "AKBNK", "name": "Akbank", "assetClass": "stock", "market": "turkey"},
    {"symbol": "ASELS.IS", "display": "ASELS", "name": "Aselsan", "assetClass": "stock", "market": "turkey"},
    {"symbol": "BIMAS.IS", "display": "BIMAS", "name": "BÄ°M", "assetClass": "stock", "market": "turkey"},
    {"symbol": "KCHOL.IS", "display": "KCHOL", "name": "KoÃ§ Holding", "assetClass": "stock", "market": "turkey"},
    {"symbol": "TUPRS.IS", "display": "TUPRS", "name": "TÃ¼praÅŸ", "assetClass": "stock", "market": "turkey"},
    {"symbol": "EREGL.IS", "display": "EREGL", "name": "EreÄŸli Demir Ã‡elik", "assetClass": "stock", "market": "turkey"},
    {"symbol": "SISE.IS", "display": "SISE", "name": "ÅiÅŸecam", "assetClass": "stock", "market": "turkey"},
    # Turkey (seed coverage)
    {"symbol": "ISCTR.IS", "display": "ISCTR", "name": "TÃ¼rkiye Ä°ÅŸ BankasÄ±", "assetClass": "stock", "market": "turkey"},
    {"symbol": "SAHOL.IS", "display": "SAHOL", "name": "SabancÄ± Holding", "assetClass": "stock", "market": "turkey"},
    {"symbol": "FROTO.IS", "display": "FROTO", "name": "Ford Otosan", "assetClass": "stock", "market": "turkey"},
    {"symbol": "PETKM.IS", "display": "PETKM", "name": "Petkim", "assetClass": "stock", "market": "turkey"},
    {"symbol": "YKBNK.IS", "display": "YKBNK", "name": "YapÄ± Kredi", "assetClass": "stock", "market": "turkey"},

    # US (live core)
    {"symbol": "AAPL", "display": "AAPL", "name": "Apple", "assetClass": "stock", "market": "us"},
    {"symbol": "MSFT", "display": "MSFT", "name": "Microsoft", "assetClass": "stock", "market": "us"},
    {"symbol": "NVDA", "display": "NVDA", "name": "Nvidia", "assetClass": "stock", "market": "us"},
    {"symbol": "TSLA", "display": "TSLA", "name": "Tesla", "assetClass": "stock", "market": "us"},
    {"symbol": "AMZN", "display": "AMZN", "name": "Amazon", "assetClass": "stock", "market": "us"},
    {"symbol": "META", "display": "META", "name": "Meta", "assetClass": "stock", "market": "us"},
    {"symbol": "GOOGL", "display": "GOOGL", "name": "Alphabet", "assetClass": "stock", "market": "us"},
    {"symbol": "AMD", "display": "AMD", "name": "AMD", "assetClass": "stock", "market": "us"},
    # US (seed coverage)
    {"symbol": "NFLX", "display": "NFLX", "name": "Netflix", "assetClass": "stock", "market": "us"},
    {"symbol": "JPM", "display": "JPM", "name": "JPMorgan Chase", "assetClass": "stock", "market": "us"},
    {"symbol": "XOM", "display": "XOM", "name": "Exxon Mobil", "assetClass": "stock", "market": "us"},
    {"symbol": "BAC", "display": "BAC", "name": "Bank of America", "assetClass": "stock", "market": "us"},
    {"symbol": "KO", "display": "KO", "name": "Coca-Cola", "assetClass": "stock", "market": "us"},
    {"symbol": "PFE", "display": "PFE", "name": "Pfizer", "assetClass": "stock", "market": "us"},
    {"symbol": "ORCL", "display": "ORCL", "name": "Oracle", "assetClass": "stock", "market": "us"},

    # Precious (live core)
    {"symbol": "GC=F", "display": "XAU", "name": "AltÄ±n Vadeli", "assetClass": "commodity", "market": "precious"},
    {"symbol": "SI=F", "display": "XAG", "name": "GÃ¼mÃ¼ÅŸ Vadeli", "assetClass": "commodity", "market": "precious"},
    {"symbol": "PL=F", "display": "PLATIN", "name": "Platin Vadeli", "assetClass": "commodity", "market": "precious"},
    {"symbol": "PA=F", "display": "PALADYUM", "name": "Paladyum Vadeli", "assetClass": "commodity", "market": "precious"},
    # Precious (seed coverage)
    {"symbol": "HG=F", "display": "COPPER", "name": "BakÄ±r Vadeli", "assetClass": "commodity", "market": "precious"},
    {"symbol": "GLD", "display": "GLD", "name": "SPDR Gold Shares", "assetClass": "etf", "market": "precious"},
    {"symbol": "SLV", "display": "SLV", "name": "iShares Silver Trust", "assetClass": "etf", "market": "precious"},
    {"symbol": "GDX", "display": "GDX", "name": "VanEck Gold Miners", "assetClass": "etf", "market": "precious"},
    {"symbol": "IAU", "display": "IAU", "name": "iShares Gold Trust", "assetClass": "etf", "market": "precious"},
    {"symbol": "PPLT", "display": "PPLT", "name": "Platinum ETF", "assetClass": "etf", "market": "precious"},
    {"symbol": "PALL", "display": "PALL", "name": "Palladium ETF", "assetClass": "etf", "market": "precious"},
    {"symbol": "NEM", "display": "NEM", "name": "Newmont", "assetClass": "stock", "market": "precious"},
    {"symbol": "GOLD", "display": "GOLD", "name": "Barrick Gold", "assetClass": "stock", "market": "precious"},
    {"symbol": "AEM", "display": "AEM", "name": "Agnico Eagle", "assetClass": "stock", "market": "precious"},
    {"symbol": "AG", "display": "AG", "name": "First Majestic Silver", "assetClass": "stock", "market": "precious"},

    # Energy (live core)
    {"symbol": "CL=F", "display": "WTI", "name": "Ham Petrol WTI", "assetClass": "commodity", "market": "energy"},
    {"symbol": "BZ=F", "display": "BRENT", "name": "Brent Petrol", "assetClass": "commodity", "market": "energy"},
    {"symbol": "NG=F", "display": "NATGAS", "name": "DoÄŸal Gaz", "assetClass": "commodity", "market": "energy"},
    {"symbol": "XLE", "display": "XLE", "name": "Enerji ETF", "assetClass": "etf", "market": "energy"},
    # Energy (seed coverage)
    {"symbol": "XOP", "display": "XOP", "name": "Oil & Gas Exploration ETF", "assetClass": "etf", "market": "energy"},
    {"symbol": "VDE", "display": "VDE", "name": "Vanguard Energy ETF", "assetClass": "etf", "market": "energy"},
    {"symbol": "OXY", "display": "OXY", "name": "Occidental Petroleum", "assetClass": "stock", "market": "energy"},
    {"symbol": "CVX", "display": "CVX", "name": "Chevron", "assetClass": "stock", "market": "energy"},
    {"symbol": "COP", "display": "COP", "name": "ConocoPhillips", "assetClass": "stock", "market": "energy"},
    {"symbol": "SHEL", "display": "SHEL", "name": "Shell", "assetClass": "stock", "market": "energy"},
    {"symbol": "BP", "display": "BP", "name": "BP", "assetClass": "stock", "market": "energy"},
    {"symbol": "EOG", "display": "EOG", "name": "EOG Resources", "assetClass": "stock", "market": "energy"},
    {"symbol": "HAL", "display": "HAL", "name": "Halliburton", "assetClass": "stock", "market": "energy"},
    {"symbol": "MPC", "display": "MPC", "name": "Marathon Petroleum", "assetClass": "stock", "market": "energy"},
    {"symbol": "PSX", "display": "PSX", "name": "Phillips 66", "assetClass": "stock", "market": "energy"},

    # Forex (live core)
    {"symbol": "EURUSD=X", "display": "EURUSD", "name": "Euro / Dolar", "assetClass": "forex", "market": "forex"},
    {"symbol": "GBPUSD=X", "display": "GBPUSD", "name": "Sterlin / Dolar", "assetClass": "forex", "market": "forex"},
    {"symbol": "JPY=X", "display": "USDJPY", "name": "Dolar / Yen", "assetClass": "forex", "market": "forex"},
    {"symbol": "TRY=X", "display": "USDTRY", "name": "Dolar / TL", "assetClass": "forex", "market": "forex"},
    # Forex (seed coverage)
    {"symbol": "AUDUSD=X", "display": "AUDUSD", "name": "Avustralya DolarÄ± / ABD DolarÄ±", "assetClass": "forex", "market": "forex"},
    {"symbol": "NZDUSD=X", "display": "NZDUSD", "name": "Yeni Zelanda DolarÄ± / ABD DolarÄ±", "assetClass": "forex", "market": "forex"},
    {"symbol": "USDCAD=X", "display": "USDCAD", "name": "ABD DolarÄ± / Kanada DolarÄ±", "assetClass": "forex", "market": "forex"},
    {"symbol": "USDCHF=X", "display": "USDCHF", "name": "ABD DolarÄ± / Ä°sviÃ§re FrangÄ±", "assetClass": "forex", "market": "forex"},
    {"symbol": "EURGBP=X", "display": "EURGBP", "name": "Euro / Sterlin", "assetClass": "forex", "market": "forex"},
    {"symbol": "EURJPY=X", "display": "EURJPY", "name": "Euro / Yen", "assetClass": "forex", "market": "forex"},
    {"symbol": "GBPJPY=X", "display": "GBPJPY", "name": "Sterlin / Yen", "assetClass": "forex", "market": "forex"},
    {"symbol": "EURTRY=X", "display": "EURTRY", "name": "Euro / TL", "assetClass": "forex", "market": "forex"},
    {"symbol": "CADJPY=X", "display": "CADJPY", "name": "Kanada DolarÄ± / Yen", "assetClass": "forex", "market": "forex"},
    {"symbol": "AUDJPY=X", "display": "AUDJPY", "name": "Avustralya DolarÄ± / Yen", "assetClass": "forex", "market": "forex"},
    {"symbol": "CHFJPY=X", "display": "CHFJPY", "name": "Ä°sviÃ§re FrangÄ± / Yen", "assetClass": "forex", "market": "forex"},

    # Indices (live core)
    {"symbol": "^GSPC", "display": "S&P500", "name": "S&P 500", "assetClass": "index", "market": "index"},
    {"symbol": "^IXIC", "display": "NASDAQ", "name": "Nasdaq Composite", "assetClass": "index", "market": "index"},
    {"symbol": "^DJI", "display": "DOW", "name": "Dow Jones", "assetClass": "index", "market": "index"},
    {"symbol": "^VIX", "display": "VIX", "name": "VIX Risk Endeksi", "assetClass": "index", "market": "index"},
    # Indices (seed coverage)
    {"symbol": "^FTSE", "display": "FTSE100", "name": "FTSE 100", "assetClass": "index", "market": "index"},
    {"symbol": "^GDAXI", "display": "DAX", "name": "DAX", "assetClass": "index", "market": "index"},
    {"symbol": "^FCHI", "display": "CAC40", "name": "CAC 40", "assetClass": "index", "market": "index"},
    {"symbol": "^N225", "display": "NIKKEI225", "name": "Nikkei 225", "assetClass": "index", "market": "index"},
    {"symbol": "^HSI", "display": "HANGSENG", "name": "Hang Seng", "assetClass": "index", "market": "index"},
    {"symbol": "^STOXX50E", "display": "EUROSTOXX50", "name": "Euro Stoxx 50", "assetClass": "index", "market": "index"},
    {"symbol": "^RUT", "display": "RUSSELL2000", "name": "Russell 2000", "assetClass": "index", "market": "index"},
    {"symbol": "^NYA", "display": "NYSECOMPOSITE", "name": "NYSE Composite", "assetClass": "index", "market": "index"},
    {"symbol": "^BSESN", "display": "SENSEX", "name": "BSE Sensex", "assetClass": "index", "market": "index"},
    {"symbol": "^BVSP", "display": "BOVESPA", "name": "Bovespa", "assetClass": "index", "market": "index"},
    {"symbol": "^KS11", "display": "KOSPI", "name": "KOSPI", "assetClass": "index", "market": "index"},

    # ETFs (live core)
    {"symbol": "QQQ", "display": "QQQ", "name": "Nasdaq ETF", "assetClass": "etf", "market": "etf"},
    {"symbol": "SPY", "display": "SPY", "name": "S&P 500 ETF", "assetClass": "etf", "market": "etf"},
    {"symbol": "GLD", "display": "GLD", "name": "AltÄ±n ETF", "assetClass": "etf", "market": "etf"},
    {"symbol": "TLT", "display": "TLT", "name": "ABD Tahvil ETF", "assetClass": "etf", "market": "etf"},
    # ETF (seed coverage)
    {"symbol": "IWM", "display": "IWM", "name": "Russell 2000 ETF", "assetClass": "etf", "market": "etf"},
    {"symbol": "DIA", "display": "DIA", "name": "Dow ETF", "assetClass": "etf", "market": "etf"},
    {"symbol": "VTI", "display": "VTI", "name": "Total Market ETF", "assetClass": "etf", "market": "etf"},
    {"symbol": "XLK", "display": "XLK", "name": "Technology ETF", "assetClass": "etf", "market": "etf"},
    {"symbol": "XLF", "display": "XLF", "name": "Financial ETF", "assetClass": "etf", "market": "etf"},
    {"symbol": "XLI", "display": "XLI", "name": "Industrial ETF", "assetClass": "etf", "market": "etf"},
    {"symbol": "XLY", "display": "XLY", "name": "Consumer Discretionary ETF", "assetClass": "etf", "market": "etf"},
    {"symbol": "XLV", "display": "XLV", "name": "Healthcare ETF", "assetClass": "etf", "market": "etf"},
    {"symbol": "XLU", "display": "XLU", "name": "Utilities ETF", "assetClass": "etf", "market": "etf"},
    {"symbol": "EEM", "display": "EEM", "name": "Emerging Markets ETF", "assetClass": "etf", "market": "etf"},
    {"symbol": "SMH", "display": "SMH", "name": "Semiconductor ETF", "assetClass": "etf", "market": "etf"},
]

